name: flutter_presentation_display
description: A Flutter plugin designed to handling secondary (presentation) display
version: 2.0.4
repository: https://github.com/elrizwiraswara/flutter_presentation_display

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.elriztechnology.flutter_presentation_display
        pluginClass: FlutterPresentationDisplayPlugin

platforms:
  android:

topics:
  - secondary-display
  - presentation-display
  - display-manager
  - display-plugin
  - multiple-displays